{{- if .Values.storage.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.storage.persistentClaimName | default (include "matrix.fullname" .) }}"
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- $sc := .Values.storage.storageClass }}
  {{- if eq $sc nil }}{{ $sc = .Values.global.storageClass }}{{ end }}
  {{- if ne $sc nil }}
  storageClassName: {{ $sc | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
{{- end }}
