{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
{{- $name := include "matrix.postgresql.fullname" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $password := "" }}
{{- if $existing }}
{{- $password = index $existing.data "password" | b64dec }}
{{- else }}
{{- $password = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $password | b64enc | quote }}
{{- end }}
